#!/bin/bash
# Aide-mémoire - Commandes pour l'implémentation du rôle admin

echo "=========================================="
echo "  IMPLÉMENTATION RÔLE ADMIN"
echo "=========================================="
echo ""

echo "1️⃣  EXÉCUTER LA MIGRATION SQL"
echo "────────────────────────────"
echo ""
echo "Option A - Via Supabase CLI:"
echo "  $ supabase migration up"
echo ""
echo "Option B - Manuelle dans Supabase Console:"
echo "  • Allez sur https://supabase.com"
echo "  • Sélectionnez votre projet"
echo "  • SQL Editor → New Query"
echo "  • Copiez le contenu de: supabase/migrations/20260111_add_admin_role.sql"
echo "  • Cliquez RUN"
echo ""
echo "Option C - Via psql (si disponible):"
echo "  $ psql -h db.xxxxx.supabase.co -U postgres < supabase/migrations/20260111_add_admin_role.sql"
echo ""

echo "2️⃣  VÉRIFIER QUE LA MIGRATION A FONCTIONNÉ"
echo "──────────────────────────────────────────"
echo ""
echo "Exécutez cette requête dans Supabase SQL Editor:"
echo ""
echo "  SELECT id, username, is_admin FROM profiles WHERE is_admin = TRUE;"
echo ""
echo "Vous devriez voir votre utilisateur avec is_admin = TRUE"
echo ""

echo "3️⃣  TESTER EN DÉVELOPPEMENT"
echo "──────────────────────────"
echo ""
echo "  $ npm install"
echo "  $ npm run dev"
echo ""
echo "Visitez:"
echo "  • http://localhost:3000/profile"
echo "  • http://localhost:3000/communaute"
echo "  • http://localhost:3000/annonces"
echo ""
echo "Vérifiez que le badge 👑 Admin apparaît"
echo ""

echo "4️⃣  DÉPLOYER EN PRODUCTION"
echo "─────────────────────────"
echo ""
echo "  $ git add ."
echo "  $ git commit -m 'feat: add admin role with badge'"
echo "  $ git push origin main"
echo ""

echo "5️⃣  VÉRIFIER EN PRODUCTION"
echo "────────────────────────"
echo ""
echo "Visitez votre site de production et vérifiez:"
echo "  • Page de profil - badge visible"
echo "  • Posts dans la communauté - badge visible"
echo "  • Annonces - badge visible"
echo "  • Services - badge visible"
echo ""

echo "=========================================="
echo "  FICHIERS IMPORTANTS"
echo "=========================================="
echo ""
echo "Migration SQL:"
echo "  supabase/migrations/20260111_add_admin_role.sql"
echo ""
echo "Documentation complète:"
echo "  • QUICK_START_ADMIN_ROLE.md"
echo "  • RESUME_IMPLEMENTATION_ADMIN.md"
echo "  • CHECKLIST_ADMIN_IMPLEMENTATION.md"
echo "  • OVERVIEW_ADMIN_IMPLEMENTATION.md"
echo "  • IMPLEMENTATION_ADMIN_ROLE.md"
echo "  • README_ADMIN_ROLE.txt"
echo ""

echo "=========================================="
echo "  COMMANDES UTILES"
echo "=========================================="
echo ""
echo "Vérifier la liste des migrations:"
echo "  $ supabase migration list"
echo ""
echo "Générer les types TypeScript:"
echo "  $ supabase gen types typescript > app/types/supabase.ts"
echo ""
echo "Vérifier la colonne is_admin existe:"
echo "  $ supabase db pull"
echo ""
echo "Reset la base de données (dev seulement):"
echo "  $ supabase db reset"
echo ""

echo "=========================================="
echo "  DÉPANNAGE"
echo "=========================================="
echo ""
echo "Le badge n'apparaît pas?"
echo ""
echo "1. Vérifiez que la migration a été exécutée:"
echo "   SELECT column_name FROM information_schema.columns"
echo "   WHERE table_name='profiles' AND column_name='is_admin';"
echo ""
echo "2. Vérifiez que votre utilisateur a is_admin = TRUE:"
echo "   SELECT id, username, is_admin FROM profiles"
echo "   WHERE id = '7169064c-25d9-4143-95ca-bbca16316ab7';"
echo ""
echo "3. Videz le cache du navigateur: Ctrl+Shift+Suppr"
echo ""
echo "4. Rechargez la page: F5"
echo ""
echo "5. Vérifiez les erreurs: F12 → Console"
echo ""

echo "=========================================="
echo "  STATUT"
echo "=========================================="
echo ""
echo "✅ Implémentation complétée"
echo "✅ Prêt pour production"
echo "✅ Documentation fournie"
echo "✅ Tests possibles"
echo ""
echo "Prochaine étape: Exécutez la migration SQL!"
echo ""
echo "=========================================="
